name: Any Commit Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run My Custom Script
        run: |
          # Add your custom script or commands here
          echo "This workflow runs on any commit."
      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Initialize CodeQL Analysis
        run: |
          codeql database init my-database --language=python
          codeql database finalize my-database
        working-directory: ${{github.workspace}}

      - name: Analyze Code with CodeQL
        run: |
          codeql analyze my-database --format=sarif-latest --output=results.sarif
        working-directory: ${{github.workspace}}

      - name: Upload Analysis Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

