name: CodeQL Analysis

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Analyze
      uses: github/codeql-action/analyze@v2

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeql-results.sarif
    - name: List Files in Workspace
      run: ls -R

