name: Any Commit Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run My Custom Script
        run: |
          # Add your custom script or commands here
          echo "This workflow runs on any commit."
